### ISSUE TITLE
Azure Web App using Docker with JSReport Azure Storage

### ISSUE THREAD

**Issue by LukeBillo** [jsreport/jsreport-azure-storage#1]
When using the JSReport dockerfile (https://github.com/jsreport/jsreport/blob/master/docker/full/Dockerfile) it includes the azure storage extensions by default. I've been trying to use these in an Azure Web App, but have no way of setting the environment variables for the storage persistence; to my understanding they should be set as follows: 

Azure Portal -> Web App -> Application Settings -> Add new setting, then name it "extensions:azure-storage:accountName" except Azure doesn't allow hyphens in the variables.

Is there any way around this? I know you can set environment variables using the dockerfile, but would like to avoid it so that maintaining it isn't an issue.

**Comment by bjrmatos** [comment]
> "extensions:azure-storage:accountName" except Azure doesn't allow hyphens in the variables.
> 
> Is there any way around this? I know you can set environment variables using the dockerfile, but would like to avoid it so that maintaining it isn't an issue.

yes, this [section of config docs](https://jsreport.net/learn/configuration#configuring-extensions) mention that we support camel case form of extensions with hyphens in its name, so you can set an env var like this `extensions:azureStorage:accountName` too if hyphens in causing problems.

let me know how it goes.

**Comment by LukeBillo** [comment]
That worked great, thanks! 👍

**Comment by LukeBillo** [comment]
Update: After adding the environment variables, I seem to get the following error / stack trace when starting up the docker container:

```
2018-05-15T08:01:32.324662598Z 2018-05-15T08:01:32.324Z - [32minfo[39m: fs store is persisting using azure-storage
2018-05-15T08:01:32.450330552Z 2018-05-15T08:01:32.450Z - [32minfo[39m: fs store is synchronizing using azure-sb
2018-05-15T08:01:32.627461250Z 2018-05-15T08:01:32.627Z - [32minfo[39m: fs store is loading data
2018-05-15T08:01:34.373228658Z 2018-05-15T08:01:34.373Z - [31merror[39m: Error occured during reporter init StorageError: The blob type is invalid for this operation.
2018-05-15T08:01:34.373281259Z RequestId:9dc123f8-301e-008c-3522-ec4ee7000000
2018-05-15T08:01:34.373288959Z Time:2018-05-15T08:01:34.3526037Z
2018-05-15T08:01:34.373295859Z     at Function.StorageServiceClient._normalizeError (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1189:23)
2018-05-15T08:01:34.373303059Z     at BlobService.StorageServiceClient._processResponse (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/azure-storage/lib/common/services/storageserviceclient.js:736:50)
2018-05-15T08:01:34.373310259Z     at Request.processResponseCallback [as _callback] (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/azure-storage/lib/common/services/storageserviceclient.js:311:37)
2018-05-15T08:01:34.373329359Z     at Request.self.callback (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/request/request.js:188:22)
2018-05-15T08:01:34.373336459Z     at emitTwo (events.js:126:13)
2018-05-15T08:01:34.373343359Z     at Request.emit (events.js:214:7)
2018-05-15T08:01:34.373350259Z     at Request.<anonymous> (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/request/request.js:1171:10)
2018-05-15T08:01:34.373357659Z     at emitOne (events.js:116:13)
2018-05-15T08:01:34.373364859Z     at Request.emit (events.js:211:7)
2018-05-15T08:01:34.373371759Z     at IncomingMessage.<anonymous> (/app/node_modules/jsreport-fs-store-azure-storage-persistence/node_modules/request/request.js:1091:12)
2018-05-15T08:01:34.373379059Z     at Object.onceWrapper (events.js:313:30)
2018-05-15T08:01:34.373385959Z     at emitNone (events.js:111:20)
2018-05-15T08:01:34.373392759Z     at IncomingMessage.emit (events.js:208:7)
2018-05-15T08:01:34.373399559Z     at endReadableNT (_stream_readable.js:1064:12)
2018-05-15T08:01:34.373406559Z     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-05-15T08:01:34.373422959Z     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Is there a variable I'm missing here?

**Comment by pofider** [comment]
Hm. Don't you have existing blobs in the container?

You are asking in this repository. But the error comes from [jsreport-fs-store-azure-storage-persistence](https://github.com/jsreport/jsreport-fs-store-azure-storage-persistence). This repository is about persisting blobs from [reports extension](https://github.com/jsreport/jsreport-reports).
I believe you are using [this config](https://jsreport.net/learn/fs-store#azure-storage) to persist templates in azure blob storage?

**Comment by LukeBillo** [comment]
Yes, that's the configuration we're using. I'll repost an issue in the correct repo with more information.

Please see [here](https://github.com/jsreport/jsreport-fs-store-azure-storage-persistence/issues/1)
